<a href="https://colab.research.google.com/github/KBVYSHNAVI/Python/blob/main/Pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

data = np.array(['g', 'e', 'e', 'k', 's'])
s = pd.Series(data)
print("Pandas Series:")
print(s)

Pandas Series:
0    g
1    e
2    e
3    k
4    s
dtype: object

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving data-.csv to data-.csv

In [ ]:
df = pd.read_csv("data-.csv")
print(df.head())

    name  age     city category  sales  a   b
0   John   25    Delhi        A    200  5  10
1   Riya   22   Mumbai        B    120  2   3
2   Aman   30     Pune        A    250  7   8
3   Neha   27  Kolkata        C    300  4   6
4  Arjun   35   Jaipur        B    200  1   9

In [ ]:
#viewing the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      5 non-null      object
 1   age       5 non-null      int64
 2   city      5 non-null      object
 3   category  5 non-null      object
 4   sales     5 non-null      int64
 5   a         5 non-null      int64
 6   b         5 non-null      int64
dtypes: int64(4), object(3)
memory usage: 412.0+ bytes

In [ ]:
#Handling the missing data
print(df.isnull().sum())
df = df.fillna(0)

name        0
age         0
city        0
category    0
sales       0
a           0
b           0
dtype: int64

In [ ]:
#filtering the data
ages = df[df['age'] > 25]
print(ages)

    name  age     city category  sales  a  b
2   Aman   30     Pune        A    250  7  8
3   Neha   27  Kolkata        C    300  4  6
4  Arjun   35   Jaipur        B    200  1  9

In [ ]:
#adding and removing columns
df['total'] = df['a'] + df['b']
print(df.head())

    name  age     city category  sales  a   b  total
0   John   25    Delhi        A    200  5  10     15
1   Riya   22   Mumbai        B    120  2   3      5
2   Aman   30     Pune        A    250  7   8     15
3   Neha   27  Kolkata        C    300  4   6     10
4  Arjun   35   Jaipur        B    200  1   9     10

In [ ]:
res = df.groupby('category')['sales'].sum()
print(res)

category
A    450
B    320
C    300
Name: sales, dtype: int64

Creating a Pandas Dataframe

In [ ]:
import pandas as pd
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [ ]:
#creating data frame
import pandas as pd
lst = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks']
df = pd.DataFrame(lst)
print(df)

        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

In [ ]:
#creating dataframe from dict of numpy array
import numpy as np
import pandas as pd

data = { 'A': np.array([1, 4, 7]),
         'B': np.array([2, 5, 8]),
         'C': np.array([3, 6, 9]) }
df = pd.DataFrame(data)
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
#Creating a datframe from a list of dictionaries
data=[
    {'name':'vyshu','degree':'B.tech','branch':'AIML','id' : 323},
    {'name':'Joshna','degree':'B.tech','branch':'It','id' : 300},
    {'name':'Purandhini','degree':'B.tech','branch':'EEE','id' : 296},
    {'name':'Harshini','degree':'B.tech','branch':'AIML','id' : 289},
    {'name':'Jyotsna','degree':'B.tech','branch':'Devops','id' : 284},
    {'name':'Mounika','degree':'B.tech','branch':'DS','id' : 269},
    {'name':'Charishma','degree':'B.tech','branch':'ECE','id' :279},
    {'name':'Agape','degree':'B.tech','branch':'Cloud','id' : 270},
]
df = pd.DataFrame(data)
print(df)

         name  degree  branch   id
0       vyshu  B.tech    AIML  323
1      Joshna  B.tech      It  300
2  Purandhini  B.tech     EEE  296
3    Harshini  B.tech    AIML  289
4     Jyotsna  B.tech  Devops  284
5     Mounika  B.tech      DS  269
6   Charishma  B.tech     ECE  279
7       Agape  B.tech   Cloud  270

Different ways to create dataFrame

In [ ]:
#creating a datfreame using dictionaries
data = {
    'Name' :['vyshu','harshitha','nithya','krish','vasavi'],
    'Age' : [20,21,22,19,6]
}
df = pd.DataFrame(data)
print(df)

        Name  Age
0      vyshu   20
1  harshitha   21
2     nithya   22
3      krish   19
4     vasavi    6

In [ ]:
import pandas as pd

# Initialize data of lists
data = [{'b': 2, 'c': 3}, {'a': 10, 'b': 20, 'c': 30}]

# Creates pandas DataFrame by passing
# Lists of dictionaries and row index.
df = pd.DataFrame(data, index=['first', 'second'])

print(df)

         b   c     a
first    2   3   NaN
second  20  30  10.0

In [ ]:
import pandas as pd

# Initialize data to Dicts of series.
d = {'one': pd.Series([10, 20, 30, 40],
                      index=['a', 'b', 'c', 'd']),
     'two': pd.Series([10, 20, 30, 40],
                      index=['a', 'b', 'c', 'd'])}

# creates Dataframe.
df = pd.DataFrame(d)

print(df)

   one  two
a   10   10
b   20   20
c   30   30
d   40   40

In [ ]:
#create a datfrane by using the proving index label explicitly
import pandas as pd

# initialize data of lists.
data = {'Name': ['Tom', 'Jack', 'nick', 'juli'],
        'marks': [99, 98, 95, 90]}

# Creates pandas DataFrame.
df = pd.DataFrame(data, index=['rank1',
                               'rank2',
                               'rank3',
                               'rank4'])

# print the data
print(df)

       Name  marks
rank1   Tom     99
rank2  Jack     98
rank3  nick     95
rank4  juli     90

Accessing elements in pandas series

In [ ]:
# import pandas and numpy
import pandas as pd
import numpy as np

# creating simple array
data = np.array(['g', 'e', 'e', 'k', 's', 'f',
                 'o', 'r', 'g', 'e', 'e', 'k', 's'])
ser = pd.Series(data)
# retrieve the first element
print(ser[0])

g

In [ ]:
print(ser[:5])

0    g
1    e
2    e
3    k
4    s
dtype: object

In [ ]:
print(ser[-10:])

3     k
4     s
5     f
6     o
7     r
8     g
9     e
10    e
11    k
12    s
dtype: object

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving data-.csv to data- (1).csv

In [ ]:
# importing pandas module
import pandas as pd

# making data frame
df = pd.read_csv("data-.csv")

ser = pd.Series(df['name'])
ser.head(10)

0     John
1     Riya
2     Aman
3     Neha
4    Arjun
Name: name, dtype: object

In [ ]:
# get first five names
ser[:3]

0    John
1    Riya
2    Aman
Name: name, dtype: object

In [ ]:
ser[[0, 1, 3, 4]]

0     John
1     Riya
3     Neha
4    Arjun
Name: name, dtype: object

In [ ]:
#adding 2 series
import pandas as pd
s1 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
s2 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])

# Adding the two Series
result = s1 + s2
print(result)

a    11
b    22
c    33
dtype: int64

In [ ]:
#comparision operations and checking equality
import pandas as pd
s1 = pd.Series([10, 20, 30])
s2 = pd.Series([1, 2, 3])

# Adding the two Series
result = s1==s2
print(result)

0    False
1    False
2    False
dtype: bool

In [ ]:
#subtracting dat frames
import pandas as pd
df1 = pd.DataFrame({'A': [10, 20, 30], 'B': [40, 50, 60]})
df2 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})

# Subtracting the DataFrames
result = df1 - df2
print(result)

    A   B
0   9  36
1  18  45
2  27  54

In [ ]:
#comparision operations
import pandas as pd
df1 = pd.DataFrame({'A': [10, 20, 30], 'B': [40, 50, 60]})
df2 = pd.DataFrame({'A': [5, 15, 35], 'B': [30, 60, 55]})

# Checking if elements of df1 are greater than df2
result = df1 > df2
print(result)

       A      B
0   True   True
1   True  False
2  False   True

In [ ]:
#logical operations
import pandas as pd
s1 = pd.Series([True, False, True])
s2 = pd.Series([False, False, True])

# Applying logical AND
result = s1 & s2
print(result)

0    False
1    False
2     True
dtype: bool

In [ ]:
#addition with a number
import pandas as pd
df1 = pd.DataFrame({'A': [1, 2, None], 'B': [4, None, 6]})
df2 = pd.DataFrame({'A': [1, None, 3], 'B': [None, 5, 6]})

# Adding the DataFrames
result = df1 + df2
print(result)

     A     B
0  2.0   NaN
1  NaN   NaN
2  NaN  12.0

In [ ]:
#modifying the indexes
data = pd.Series([10,20,30,40],index=['a','b','c','d'])
#accessing the index
print("Original index: ",data.index)
#modifyint the index
data.index = ['W','X','Y','Z']
print("Modified Series:\n",data)

Original index:  Index(['a', 'b', 'c', 'd'], dtype='object')
Modified Series:
 W    10
X    20
Y    30
Z    40
dtype: int64

In [ ]:
#Assigning duplicate Index labels
import pandas as pd

series = pd.Series(['New York', 'Chicago', 'Toronto', 'Lisbon'])

# Creating the row axis labels
series.index = ['City 1', 'City 1', 'City 3', 'City 3']
print(series)

City 1    New York
City 1     Chicago
City 3     Toronto
City 3      Lisbon
dtype: object

In [ ]:
#retrieving the index labels
Date = ['1/1/2018', '2/1/2018', '3/1/2018', '4/1/2018']
idx_name = ['Day 1', 'Day 2', 'Day 3', 'Day 4']

sr = pd.Series(data = Date,index = idx_name)
print(sr.index)

Index(['Day 1', 'Day 2', 'Day 3', 'Day 4'], dtype='object')

In [ ]:
#resetting index default
import pandas as pd

Date = ['1/1/2018', '2/1/2018', '3/1/2018', '4/1/2018']
idx_name = ['Day 1', 'Day 2', 'Day 3', 'Day 4']

sr = pd.Series(data = Date,        # Series Data
              index = idx_name   # Index
              )

# Resetting index to default
sr.reset_index(drop=True, inplace=True)
print(sr)

0    1/1/2018
1    2/1/2018
2    3/1/2018
3    4/1/2018
dtype: object

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving data-.csv to data-.csv

In [ ]:
#adding new rows
import pandas as pd
df = pd.read_csv('data-.csv')

new_row = {
    'Name': 'nithya',
    'Team': 'noen',
    'Number': 3,
    'Position': 'PG',
    'Age': 33,
    'College': 'MIT',
    'Salary': 99999
}
df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
df.tail(2)

,name,age,city,category,sales,a,b,Name,Team,Number,Position,Age,College,Salary
4,Arjun,35.0,Jaipur,B,200.0,1.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nithya,noen,3.0,PG,33.0,MIT,99999.0

In [ ]:
#getting columns
import pandas as pd

df = pd.DataFrame({
    'Name': ['yshu', 'Joshna', 'harshitha','nithya'],
    'Team': ['Boks','poramboks'] * 2,
    'Number': [0.0, 99.0, 30.0,50.0],
})

# Get column names
res = df.columns
print(res)

Index(['Name', 'Team', 'Number'], dtype='object')

In [ ]:
df.describe()

          Number
count   4.000000
mean   44.750000
std    41.596274
min     0.000000
25%    22.500000
50%    40.000000
75%    62.250000
max    99.000000

In [ ]:
df

        Name       Team  Number
0       yshu       Boks     0.0
1     Joshna  poramboks    99.0
2  harshitha       Boks    30.0
3     nithya  poramboks    50.0

In [ ]:
list(df.columns)

['Name', 'Team', 'Number']

In [ ]:
#using keys method
# column_keys
res = df.keys()
print(res)

Index(['Name', 'Team', 'Number'], dtype='object')

In [ ]:
#sorted keys
# sorted_columns
res = sorted(df.columns)
print(res)

['Name', 'Number', 'Team']

In [ ]:
#renaming the columns
df = pd.DataFrame({'A': [10, 20], 'B': [30, 40], 'C': [50, 60]})
df.rename(columns={'A': 'X', 'B': 'Y'}, inplace=True)
print(df)

    X   Y   C
0  10  30  50
1  20  40  60

In [ ]:
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4], 'C': [5, 6]})
df = df.set_axis(['Alpha', 'Beta', 'Gamma'], axis=1)
print(df)

   Alpha  Beta  Gamma
0      1     3      5
1      2     4      6

In [ ]:
#adding prefix or suffx
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
pre = df.add_prefix('new_')
suf = df.add_suffix('_val')
print("Prefixed:\n", pre)
print("Suffixed:\n", suf)

Prefixed:
    new_A  new_B
0      1      3
1      2      4
Suffixed:
    A_val  B_val
0      1      3
1      2      4

In [ ]:
#dropping multiple columns
data = pd.DataFrame({
    'A': ['A1', 'A2', 'A3', 'A4', 'A5'],
    'B': ['B1', 'B2', 'B3', 'B4', 'B5'],
    'C': ['C1', 'C2', 'C3', 'C4', 'C5']
})
print(data)

    A   B   C
0  A1  B1  C1
1  A2  B2  C2
2  A3  B3  C3
3  A4  B4  C4
4  A5  B5  C5

In [ ]:
df = data.drop(['B', 'C'], axis=1)
df

    A
0  A1
1  A2
2  A3
3  A4
4  A5

In [ ]:
#using loc
df = data.drop(columns=data.loc[:, 'A':'B'].columns)
df

    C
0  C1
1  C2
2  C3
3  C4
4  C5

In [ ]:
#using pop method
p1 = data.pop('B')
print(p1)

0    B1
1    B2
2    B3
3    B4
4    B5
Name: B, dtype: object

In [ ]:
#unique numbers
data = {'A': ['A1', 'A2', 'A3', 'A4', 'A5'],
        'B': ['B1', 'B2', 'B3', 'B4', 'B4'],
        'C': ['C1', 'C2', 'C3', 'C3', 'C3'],
        'D': ['D1', 'D2', 'D2', 'D2', 'D2'],
        'E': ['E1', 'E1', 'E1', 'E1', 'E1']}

df = pd.DataFrame(data)
print(df)

    A   B   C   D   E
0  A1  B1  C1  D1  E1
1  A2  B2  C2  D2  E1
2  A3  B3  C3  D2  E1
3  A4  B4  C3  D2  E1
4  A5  B4  C3  D2  E1

In [ ]:
#unique method
unique_B = df['B'].unique()
print(unique_B)

['B1' 'B2' 'B3' 'B4']

In [ ]:
#nunique()-->counts number of unique values in a column
print("Unique count in A:", df['A'].nunique())
print("Unique count in B:", df['B'].nunique())
print("Unique count in C:", df['C'].nunique())
print("Unique count in D:", df['D'].nunique())

Unique count in A: 5
Unique count in B: 4
Unique count in C: 3
Unique count in D: 2

In [ ]:
#dropping the duplicate value
unique_C = df['C'].drop_duplicates()
print(unique_C)

0    C1
1    C2
2    C3
Name: C, dtype: object

In [ ]:
#value_counts
counts_D = df['D'].value_counts()
unique_D = counts_D.index
print("Value counts in D:\n", counts_D)
print("Unique values in D:", list(unique_D))

Value counts in D:
 D
D2    4
D1    1
Name: count, dtype: int64
Unique values in D: ['D2', 'D1']

In [ ]:

unique_set_D = set(df['D'])
print(unique_set_D)

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving nba.csv to nba.csv

In [ ]:
#selecting rows using .iloc & loc
import pandas as pd
data = pd.read_csv("nba.csv")
row1 = data.loc[3]
row2 = data.iloc[3]
row1==row2

Name        True
Team        True
Number      True
Position    True
Age         True
Height      True
Weight      True
College     True
Salary      True
Name: 3, dtype: bool

In [ ]:
row1

Name           R.J. Hunter
Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: 3, dtype: object

In [ ]:
row2

Name           R.J. Hunter
Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: 3, dtype: object

In [ ]:
#selecting multiple methods using iloc
data = pd.read_csv("nba.csv")
row1 = data.iloc[[4,5,6,7]]
row2 = data.iloc[4:8]
row1==row2

   Name  Team  Number  Position   Age  Height  Weight  College  Salary
4  True  True    True      True  True    True    True    False    True
5  True  True    True      True  True    True    True    False    True
6  True  True    True      True  True    True    True     True    True
7  True  True    True      True  True    True    True     True    True

In [ ]:
#selecting a single column
import pandas as pd

data = pd.read_csv("/content/nba.csv", index_col="Name")
print("Dataset")
print(data.head(5))

first = data["Age"]
print("\nSingle Column selected from Dataset")
print(first.head(5))

Dataset
                         Team  Number Position   Age Height  Weight  \
Name
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

                         College     Salary
Name
Avery Bradley              Texas  7730337.0
Jae Crowder            Marquette  6796117.0
John Holland   Boston University        NaN
R.J. Hunter        Georgia State  1148640.0
Jonas Jerebko                NaN  5000000.0

Single Column selected from Dataset
Name
Avery Bradley    25.0
Jae Crowder      25.0
John Holland     27.0
R.J. Hunter      22.0
Jonas Jerebko    29.0
Name: Age, dtype: float64

In [ ]:
#selecting multiple columns
first = data[["Age", "College", "Salary"]]
print("\nMultiple Columns selected from Dataset")
print(first.head(5))

Multiple Columns selected from Dataset
                Age            College     Salary
Name
Avery Bradley  25.0              Texas  7730337.0
Jae Crowder    25.0          Marquette  6796117.0
John Holland   27.0  Boston University        NaN
R.J. Hunter    22.0      Georgia State  1148640.0
Jonas Jerebko  29.0                NaN  5000000.0

In [ ]:
#by location based index
import pandas as pd
data = pd.read_csv("/content/nba.csv", index_col="Name")

row = data.loc["Avery Bradley"]
print(row)

Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Height                 6-2
Weight               180.0
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object

In [ ]:
#selecting all rows and specific columns
all_rows_specific_columns = data.loc[:, ["Team", "Position", "Salary"]]
print(all_rows_specific_columns)

                         Team Position     Salary
Name
Avery Bradley  Boston Celtics       PG  7730337.0
Jae Crowder    Boston Celtics       SF  6796117.0
John Holland   Boston Celtics       SG        NaN
R.J. Hunter    Boston Celtics       SG  1148640.0
Jonas Jerebko  Boston Celtics       PF  5000000.0
...                       ...      ...        ...
Shelvin Mack        Utah Jazz       PG  2433333.0
Raul Neto           Utah Jazz       PG   900000.0
Tibor Pleiss        Utah Jazz        C  2900000.0
Jeff Withey         Utah Jazz        C   947276.0
NaN                       NaN      NaN        NaN

[458 rows x 3 columns]

In [ ]:
#selecting all rows and specific columns
selection = data.iloc[:, [1, 2]]
print(selection)

               Number Position
Name
Avery Bradley     0.0       PG
Jae Crowder      99.0       SF
John Holland     30.0       SG
R.J. Hunter      28.0       SG
Jonas Jerebko     8.0       PF
...               ...      ...
Shelvin Mack      8.0       PG
Raul Neto        25.0       PG
Tibor Pleiss     21.0        C
Jeff Withey      24.0        C
NaN               NaN      NaN

[458 rows x 2 columns]

In [ ]:
#.head(): Returns the first n rows of a DataFrame
print(data.head(5))

                         Team  Number Position   Age Height  Weight  \
Name
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

                         College     Salary
Name
Avery Bradley              Texas  7730337.0
Jae Crowder            Marquette  6796117.0
John Holland   Boston University        NaN
R.J. Hunter        Georgia State  1148640.0
Jonas Jerebko                NaN  5000000.0

In [ ]:
#.tail(): Returns the last n rows of a DataFrame
print(data.tail(5))

                   Team  Number Position   Age Height  Weight College  \
Name
Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0  Butler
Raul Neto     Utah Jazz    25.0       PG  24.0    6-1   179.0     NaN
Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0     NaN
Jeff Withey   Utah Jazz    24.0        C  26.0    7-0   231.0  Kansas
NaN                 NaN     NaN      NaN   NaN    NaN     NaN     NaN

                 Salary
Name
Shelvin Mack  2433333.0
Raul Neto      900000.0
Tibor Pleiss  2900000.0
Jeff Withey    947276.0
NaN                 NaN

In [ ]:
#.at[]: Access a single value for a row/column label pair
value = data.at["Avery Bradley", "Age"]
print(value)

25.0

In [ ]:
#.query(): Query the DataFrame using a boolean expression
result = data.query("Age > 25 and College == 'Duke'")
print(result)

                                    Team  Number Position   Age Height  \
Name
Lance Thomas             New York Knicks    42.0       SF  28.0    6-8
Elton Brand           Philadelphia 76ers    42.0       PF  37.0    6-9
JJ Redick           Los Angeles Clippers     4.0       SG  31.0    6-4
Mike Dunleavy              Chicago Bulls    34.0       SG  35.0    6-9
Dahntay Jones        Cleveland Cavaliers    30.0       SG  35.0    6-6
Miles Plumlee            Milwaukee Bucks    18.0        C  27.0   6-11
Luol Deng                     Miami Heat     9.0       SF  31.0    6-9
Josh McRoberts                Miami Heat     4.0       PF  29.0   6-10
Kyle Singler       Oklahoma City Thunder     5.0       SF  28.0    6-8
Gerald Henderson  Portland Trail Blazers     9.0       SG  28.0    6-5
Mason Plumlee     Portland Trail Blazers    24.0        C  26.0   6-11

                  Weight College      Salary
Name
Lance Thomas       235.0    Duke   1636842.0
Elton Brand        254.0    Duke         NaN
JJ Redick          190.0    Duke   7085000.0
Mike Dunleavy      230.0    Duke   4500000.0
Dahntay Jones      225.0    Duke         NaN
Miles Plumlee      249.0    Duke   2109294.0
Luol Deng          220.0    Duke  10151612.0
Josh McRoberts     240.0    Duke   5543725.0
Kyle Singler       228.0    Duke   4500000.0
Gerald Henderson   215.0    Duke   6000000.0
Mason Plumlee      235.0    Duke   1415520.0

In [ ]:
#creating dataframe to slice columns
import pandas as pd
df1  = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
display(df1)

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [ ]:
#slicing the columns and reindexing
df2 = df1.reindex(columns = ['c','b'])
print(df2)

    c   b
0 NaN NaN
1 NaN NaN
2 NaN NaN

Operations

In [1]:
#pandas.Series.apply() --> it is used to apply a function to each element of a series
#it allows to transform,modify or categorize data
#Sysntax: Series.apply(func, convert_dtype=True, args=())
import pandas as pd
s = pd.Series([1, 2, 3, 4])
r = s.apply(lambda x: x * 2)
print(r)

0    2
1    4
2    6
3    8
dtype: int64

In [2]:
s = pd.Series([35, 67, 90, 45])
def f(x):
    return "Pass" if x >= 50 else "Fail"

r = s.apply(f)
print(r)

0    Fail
1    Pass
2    Pass
3    Fail
dtype: object

In [3]:
s = pd.Series([10000, 15000, 20000])
r = s.apply(lambda x: x * 1.10)
print(r)

0    11000.0
1    16500.0
2    22000.0
dtype: float64

In [5]:
#apply() to convert each numeric value into a formatted text string.
s = pd.Series([5, 10, 15])
r = s.apply(lambda x: "Value is " + str(x))
print(r)
#lambda x: "Value is " + str(x) converts number into text.
#str(x) converts numeric value into string.
#s.apply(...) applies this conversion to every element.

0     Value is 5
1    Value is 10
2    Value is 15
dtype: object

Apply function to every row in a Pandas DataFrame

In [6]:
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
df['add'] = df['A'] + df['B'] + df['C']
print(df)

   A  B  C  add
0  1  4  7   12
1  2  5  8   15
2  3  6  9   18

In [7]:
#Using .values() --> can perform fast row-wise computations using NumPy functions like np.sum().
import pandas as pd
import numpy as np

df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
df['add'] = np.sum(df[['A', 'B', 'C']].values, axis=1)
print(df)

   A  B  C  add
0  1  4  7   12
1  2  5  8   15
2  3  6  9   18

In [ ]:
#Using itertuples() --> iterates over DataFrame rows as namedtuples, offering better performance than iterrows()
import pandas as pd

df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
res = []
for row in df.itertuples(index=False):
    res.append(row.A + row.B + row.C)
df['add'] = res
print(df)

In [8]:
#using list comprehension
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
df['add'] = [a + b + c for a, b, c in zip(df['A'], df['B'], df['C'])]
print(df)

   A  B  C  add
0  1  4  7   12
1  2  5  8   15
2  3  6  9   18

In [9]:
# Creating the Series
sr = pd.Series([11, 21, 8, 18, 65, 18, 32, 10, 5, 32, None])

# Create the Index
# apply yearly frequency
index_ = pd.date_range('2010-10-09 08:45', periods = 11, freq ='Y')

# set the index
sr.index = index_

# Print the series
print(sr)

2010-12-31 08:45:00    11.0
2011-12-31 08:45:00    21.0
2012-12-31 08:45:00     8.0
2013-12-31 08:45:00    18.0
2014-12-31 08:45:00    65.0
2015-12-31 08:45:00    18.0
2016-12-31 08:45:00    32.0
2017-12-31 08:45:00    10.0
2018-12-31 08:45:00     5.0
2019-12-31 08:45:00    32.0
2020-12-31 08:45:00     NaN
Freq: YE-DEC, dtype: float64

/tmp/ipykernel_666/2977664615.py:6: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  index_ = pd.date_range('2010-10-09 08:45', periods = 11, freq ='Y')

In [10]:
#DataFrame.assign() method --> creates a new DataFrame with the specified column(s) added
import pandas as pd

# Define a dictionary containing Students data
data = {'Name': ['Pandas', 'Geeks', 'for', 'Geeks'],
        'Height': [1, 2, 3, 4],
        'Qualification': ['A', 'B', 'C', 'D']}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data)

# using assign() and passing address list as parameter
df = df.assign(address = ['NewYork', 'Chicago', 'Boston', 'Miami'])

print(df)

     Name  Height Qualification  address
0  Pandas       1             A  NewYork
1   Geeks       2             B  Chicago
2     for       3             C   Boston
3   Geeks       4             D    Miami

In [11]:
import pandas as pd

# Define a dictionary containing Students data
data = {'Name': ['Pandas', 'Geeks', 'for', 'Geeks'],
        'Height': [1, 2, 3, 4],
        'Qualification': ['A', 'B', 'C', 'D']}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data)

# Using insert() to add a column at position 2 (3rd column)
df.insert(2, "Age", [21, 23, 24, 21], True)
print(df)

     Name  Height  Age Qualification
0  Pandas       1   21             A
1   Geeks       2   23             B
2     for       3   24             C
3   Geeks       4   21             D

In [12]:
# DataFrame.truncate(before=None, after=None, axis=None, copy=True)
df = pd.DataFrame({'Weight':[45, 88, 56, 15, 71],
                   'Name':['Sam', 'Andrea', 'Alex', 'Robin', 'Kia'],
                   'Age':[14, 25, 55, 8, 21]})

# Create the index
index_ = pd.date_range('2010-10-09 08:45', periods = 5, freq ='H')

# Set the index
df.index = index_

# Print the DataFrame
print(df)

                     Weight    Name  Age
2010-10-09 08:45:00      45     Sam   14
2010-10-09 09:45:00      88  Andrea   25
2010-10-09 10:45:00      56    Alex   55
2010-10-09 11:45:00      15   Robin    8
2010-10-09 12:45:00      71     Kia   21

/tmp/ipykernel_666/3441963704.py:7: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  index_ = pd.date_range('2010-10-09 08:45', periods = 5, freq ='H')

In [13]:
# Creating the DataFrame
df = pd.DataFrame({"A":[12, 4, 5, None, 1],
                   "B":[7, 2, 54, 3, None],
                   "C":[20, 16, 11, 3, 8],
                   "D":[14, 3, None, 2, 6]})

# Create the index
index_ = ['Row_1', 'Row_2', 'Row_3', 'Row_4', 'Row_5']

# Set the index
df.index = index_

# Print the DataFrame
print(df)

          A     B   C     D
Row_1  12.0   7.0  20  14.0
Row_2   4.0   2.0  16   3.0
Row_3   5.0  54.0  11   NaN
Row_4   NaN   3.0   3   2.0
Row_5   1.0   NaN   8   6.0

In [14]:
#Cncatenating dataframes
data1 = {'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd'],
         'Mobile No': [97, 91, 58, 76]}

data2 = {'Name': ['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'],
         'Age': [22, 32, 12, 52],
         'Address': ['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
         'Qualification': ['MCA', 'Phd', 'Bcom', 'B.hons'],
         'Salary': [1000, 2000, 3000, 4000]}

df = pd.DataFrame(data1, index=[0, 1, 2, 3])

df1 = pd.DataFrame(data2, index=[2, 3, 6, 7])

print(df, "\n\n", df1)

     Name  Age    Address Qualification  Mobile No
0     Jai   27     Nagpur           Msc         97
1  Princi   24     Kanpur            MA         91
2  Gaurav   22  Allahabad           MCA         58
3    Anuj   32    Kannuaj           Phd         76

      Name  Age    Address Qualification  Salary
2  Gaurav   22  Allahabad           MCA    1000
3    Anuj   32    Kannuaj           Phd    2000
6  Dhiraj   12  Allahabad          Bcom    3000
7  Hitesh   52    Kannuaj        B.hons    4000

In [15]:
#we set axes join = inner for intersection of dataframe which keeps only the common columns.
res2 = pd.concat([df, df1], axis=1, join='inner')
res2

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
2,Gaurav,22,Allahabad,MCA,58,Gaurav,22,Allahabad,MCA,1000
3,Anuj,32,Kannuaj,Phd,76,Anuj,32,Kannuaj,Phd,2000

In [16]:
# join = outer for union of dataframe which keeps all columns from both DataFrames.
res2 = pd.concat([df, df1], axis=1, sort=False)
res2

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
0,Jai,27.0,Nagpur,Msc,97.0,NaN,NaN,NaN,NaN,NaN
1,Princi,24.0,Kanpur,MA,91.0,NaN,NaN,NaN,NaN,NaN
2,Gaurav,22.0,Allahabad,MCA,58.0,Gaurav,22.0,Allahabad,MCA,1000.0
3,Anuj,32.0,Kannuaj,Phd,76.0,Anuj,32.0,Kannuaj,Phd,2000.0
6,NaN,NaN,NaN,NaN,NaN,Dhiraj,12.0,Allahabad,Bcom,3000.0
7,NaN,NaN,NaN,NaN,NaN,Hitesh,52.0,Kannuaj,B.hons,4000.0

In [17]:
res = pd.concat([df, df1], ignore_index=True)

res

     Name  Age    Address Qualification  Mobile No  Salary
0     Jai   27     Nagpur           Msc       97.0     NaN
1  Princi   24     Kanpur            MA       91.0     NaN
2  Gaurav   22  Allahabad           MCA       58.0     NaN
3    Anuj   32    Kannuaj           Phd       76.0     NaN
4  Gaurav   22  Allahabad           MCA        NaN  1000.0
5    Anuj   32    Kannuaj           Phd        NaN  2000.0
6  Dhiraj   12  Allahabad          Bcom        NaN  3000.0
7  Hitesh   52    Kannuaj        B.hons        NaN  4000.0

In [18]:
frames = [df, df1 ]
res = pd.concat(frames, keys=['x', 'y'])
res

       Name  Age    Address Qualification  Mobile No  Salary
x 0     Jai   27     Nagpur           Msc       97.0     NaN
  1  Princi   24     Kanpur            MA       91.0     NaN
  2  Gaurav   22  Allahabad           MCA       58.0     NaN
  3    Anuj   32    Kannuaj           Phd       76.0     NaN
y 2  Gaurav   22  Allahabad           MCA        NaN  1000.0
  3    Anuj   32    Kannuaj           Phd        NaN  2000.0
  6  Dhiraj   12  Allahabad          Bcom        NaN  3000.0
  7  Hitesh   52    Kannuaj        B.hons        NaN  4000.0

In [20]:
#going to mix series and dataframe to gether
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}

df = pd.DataFrame(data1,index=[0, 1, 2, 3])

s1 = pd.Series([1000, 2000, 3000, 4000], name='Salary')

print(df, "\n\n", s1)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannuaj           Phd

 0    1000
1    2000
2    3000
3    4000
Name: Salary, dtype: int64

In [21]:
res = pd.concat([df, s1], axis=1)

res

     Name  Age    Address Qualification  Salary
0     Jai   27     Nagpur           Msc    1000
1  Princi   24     Kanpur            MA    2000
2  Gaurav   22  Allahabad           MCA    3000
3    Anuj   32    Kannuaj           Phd    4000

In [22]:
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K1', 'K0', 'K1'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}

data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K0', 'K0', 'K0'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2)


print(df, "\n\n", df1)

  key key1    Name  Age
0  K0   K0     Jai   27
1  K1   K1  Princi   24
2  K2   K0  Gaurav   22
3  K3   K1    Anuj   32

   key key1    Address Qualification
0  K0   K0     Nagpur         Btech
1  K1   K0     Kanpur           B.A
2  K2   K0  Allahabad          Bcom
3  K3   K0    Kannuaj        B.hons

In [23]:
#merging using multiple keys
res1 = pd.merge(df, df1, on=['key', 'key1'])

res1

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K2   K0  Gaurav   22  Allahabad          Bcom

MERGE METHOD	JOIN NAME	DESCRIPTION
left	LEFT OUTER JOIN	Use keys from left frame only
right	RIGHT OUTER JOIN	Use keys from right frame only
outer	FULL OUTER JOIN	Use union of keys from both frames
inner	INNER JOIN	Use intersection of keys from both frames

In [24]:
res = pd.merge(df, df1, how='left', on=['key', 'key1'])

res

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K1   K1  Princi   24        NaN           NaN
2  K2   K0  Gaurav   22  Allahabad          Bcom
3  K3   K1    Anuj   32        NaN           NaN

In [25]:
res1 = pd.merge(df, df1, how='right', on=['key', 'key1'])

res1

  key key1    Name   Age    Address Qualification
0  K0   K0     Jai  27.0     Nagpur         Btech
1  K1   K0     NaN   NaN     Kanpur           B.A
2  K2   K0  Gaurav  22.0  Allahabad          Bcom
3  K3   K0     NaN   NaN    Kannuaj        B.hons

In [26]:
res2 = pd.merge(df, df1, how='outer', on=['key', 'key1'])

res2

  key key1    Name   Age    Address Qualification
0  K0   K0     Jai  27.0     Nagpur         Btech
1  K1   K0     NaN   NaN     Kanpur           B.A
2  K1   K1  Princi  24.0        NaN           NaN
3  K2   K0  Gaurav  22.0  Allahabad          Bcom
4  K3   K0     NaN   NaN    Kannuaj        B.hons
5  K3   K1    Anuj  32.0        NaN           NaN

In [27]:
res3 = pd.merge(df, df1, how='inner', on=['key', 'key1'])

res3

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K2   K0  Gaurav   22  Allahabad          Bcom

In [28]:
#joing dataframes using join
data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32]}

data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1,index=['K0', 'K1', 'K2', 'K3'])

df1 = pd.DataFrame(data2, index=['K0', 'K2', 'K3', 'K4'])


print(df, "\n\n", df1)

      Name  Age
K0     Jai   27
K1  Princi   24
K2  Gaurav   22
K3    Anuj   32

       Address Qualification
K0  Allahabad           MCA
K2    Kannuaj           Phd
K3  Allahabad          Bcom
K4    Kannuaj        B.hons

In [29]:
res = df.join(df1)

res

      Name  Age    Address Qualification
K0     Jai   27  Allahabad           MCA
K1  Princi   24        NaN           NaN
K2  Gaurav   22    Kannuaj           Phd
K3    Anuj   32  Allahabad          Bcom

In [30]:
res1 = df.join(df1, how='outer')

res1

      Name   Age    Address Qualification
K0     Jai  27.0  Allahabad           MCA
K1  Princi  24.0        NaN           NaN
K2  Gaurav  22.0    Kannuaj           Phd
K3    Anuj  32.0  Allahabad          Bcom
K4     NaN   NaN    Kannuaj        B.hons

In [32]:
import pandas as pd

data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Key':['K0', 'K1', 'K2', 'K3']}

data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2, index=['K0', 'K2', 'K3', 'K4'])


print(df, "\n\n", df1)

     Name  Age Key
0     Jai   27  K0
1  Princi   24  K1
2  Gaurav   22  K2
3    Anuj   32  K3

       Address Qualification
K0  Allahabad           MCA
K2    Kannuaj           Phd
K3  Allahabad          Bcom
K4    Kannuaj        B.hons

In [33]:
# on argument. This allows us to specify which column(s) should be used to align the two DataFrames.
res2 = df.join(df1, on='Key')
res2

     Name  Age Key    Address Qualification
0     Jai   27  K0  Allahabad           MCA
1  Princi   24  K1        NaN           NaN
2  Gaurav   22  K2    Kannuaj           Phd
3    Anuj   32  K3  Allahabad          Bcom

In [34]:
#joining text columns into a single column in pandas

df = pd.DataFrame({'Last': ['Gaitonde', 'Singh', 'Mathur'],
                   'First': ['Ganesh', 'Sartaj', 'Anjali']})

print('Before Join')
print(df, '\n')

print('After join')
df['Name'] = df['First'].str.cat(df['Last'], sep =" ")
print(df)

Before Join
       Last   First
0  Gaitonde  Ganesh
1     Singh  Sartaj
2    Mathur  Anjali

After join
       Last   First             Name
0  Gaitonde  Ganesh  Ganesh Gaitonde
1     Singh  Sartaj     Sartaj Singh
2    Mathur  Anjali    Anjali Mathur

In [35]:
df = pd.DataFrame({'Last': ['Gaitonde', 'Singh', 'Mathur'],
                   'First': ['Ganesh', 'Sartaj', 'Anjali']})

print('Before Join')
print(df, '\n')

print('After join')
df['Name'] = df[['First', 'Last']].apply(lambda x: ' '.join(x), axis = 1)
print(df)

Before Join
       Last   First
0  Gaitonde  Ganesh
1     Singh  Sartaj
2    Mathur  Anjali

After join
       Last   First             Name
0  Gaitonde  Ganesh  Ganesh Gaitonde
1     Singh  Sartaj     Sartaj Singh
2    Mathur  Anjali    Anjali Mathur

In [36]:
#Pandas Series.equals() to compare two pandas series.
# Creating 2 pandas Series
ps1 = pd.Series([2.5, 4, 6, 8, 10, 1.75, 40])
ps2 = pd.Series([1.5, 3, 5, 7, 10, 1.75, 20])

print("Series1:")
print(ps1)
print("\nSeries2:")
print(ps2)

# Compare the series using '==' and '!='
# Relational operators
print("\nCompare the elements of the two given Series:")
print("\nEqual:")
print(ps1 == ps2)
print("\nNot Equal:")
print(ps1 != ps2)

Series1:
0     2.50
1     4.00
2     6.00
3     8.00
4    10.00
5     1.75
6    40.00
dtype: float64

Series2:
0     1.50
1     3.00
2     5.00
3     7.00
4    10.00
5     1.75
6    20.00
dtype: float64

Compare the elements of the two given Series:

Equal:
0    False
1    False
2    False
3    False
4     True
5     True
6    False
dtype: bool

Not Equal:
0     True
1     True
2     True
3     True
4    False
5    False
6     True
dtype: bool

In [37]:
# Creating 2 pandas Series
ps1 = pd.Series([2.5, 4, 6, 8, 10, 1.75, 40])
ps2 = pd.Series([1.5, 3, 5, 7, 10, 1.75, 20])

print("Series1:")
print(ps1)
print("\nSeries2:")
print(ps2)

# Comparing two series using Series.equals()
# function
print("\nResult of comparing Two Series:")
result = ps1.equals(other=ps2)
print(result)

Series1:
0     2.50
1     4.00
2     6.00
3     8.00
4    10.00
5     1.75
6    40.00
dtype: float64

Series2:
0     1.50
1     3.00
2     5.00
3     7.00
4    10.00
5     1.75
6    20.00
dtype: float64

Result of comparing Two Series:
False

Working with date and time using pandas

In [38]:
#working with dates
from datetime import date
d = date(2000,9,17)
print(d)
print(type(d))

2000-09-17
<class 'datetime.date'>

In [39]:

# Creating a Timestamp object
timestamp = pd.Timestamp('2023-10-04 15:30:00')

# Extracting the year from the Timestamp
year = timestamp.year

# Printing the extracted year
print(year)

# Extracting the month from the Timestamp
month = timestamp.month

# Printing the extracted month
print(month)

# Extracting the day from the Timestamp
day = timestamp.day

# Printing the extracted day
print(day)

2023
10
4

In [40]:
# Extracting the hour from the Timestamp
hour = timestamp.hour

# Printing the extracted hour
print(hour)

# Extracting the minute from the Timestamp
minute = timestamp.minute

# Printing the extracted minute
print(minute)
# Extracting the weekday from the Timestamp
weekday = timestamp.weekday()

# Printing the extracted weekday
print(weekday)

# Extracting the quarter from the Timestamp
quarter = timestamp.quarter

# Printing the extracted quarter
print(quarter)

15
30
2
4

In [41]:
#working with time
from datetime import time

t = time(12,50,12,40)

print(t)

print(type(t))

12:50:12.000040
<class 'datetime.time'>

In [42]:
# Creating a time period object
time_period = pd.Period('2023-10-04', freq='M')

# Extracting the year from the time period
year = time_period.year

# Printing the extracted year
print(year)

# Extracting the month from the time period
month = time_period.month

# Printing the extracted month
print(month)

# Extracting the quarter from the time period
quarter = time_period.quarter

# Printing the extracted quarter
print(quarter)

# Creating a date offset object
date_offset = pd.DateOffset(years=2, months=3, days=10)

# Adding the date offset to a Timestamp
new_timestamp = timestamp + date_offset

# Printing the new Timestamp
print(new_timestamp)

2023
10
4
2026-01-14 15:30:00

Handling Time Zones
->UTC & time zone conversion
->Time zone - aware data manipulation
->Custom time zone settings

In [44]:
import pandas as pd

# Creating a Timestamp object with a specific time zone
timestamp = pd.Timestamp(
    '2023-10-04 15:30:00',
    tz='America/New_York'
)

# Printing the Timestamp with its time zone
print("Original timestamp:")
print(timestamp)

# Converting the Timestamp to UTC
utc_timestamp = timestamp.tz_convert('UTC')

# Printing the UTC timestamp
print("\nUTC timestamp:")
print(utc_timestamp)

# Converting the UTC timestamp back to the original time zone
original_timestamp = utc_timestamp.tz_convert('America/New_York')

# Printing the original timestamp
print("\nOriginal time zone:")
print(original_timestamp)


# Creating a DatetimeIndex with a specific time zone
datetime_index = pd.DatetimeIndex(
    ['2023-10-04', '2023-10-11', '2023-10-18'],
    tz='Asia/Shanghai'
)

# Printing the DatetimeIndex with its time zone
print("\nOriginal DatetimeIndex:")
print(datetime_index)

# Converting the DatetimeIndex to UTC
utc_datetime_index = datetime_index.tz_convert('UTC')

# Printing the UTC DatetimeIndex
print("\nUTC DatetimeIndex:")
print(utc_datetime_index)

# Converting the UTC DatetimeIndex back to the original time zone
original_datetime_index = utc_datetime_index.tz_convert('Asia/Shanghai')

# Printing the original DatetimeIndex
print("\nOriginal DatetimeIndex:")
print(original_datetime_index)

Original timestamp:
2023-10-04 15:30:00-04:00

UTC timestamp:
2023-10-04 19:30:00+00:00

Original time zone:
2023-10-04 15:30:00-04:00

Original DatetimeIndex:
DatetimeIndex(['2023-10-04 00:00:00+08:00', '2023-10-11 00:00:00+08:00',
               '2023-10-18 00:00:00+08:00'],
              dtype='datetime64[ns, Asia/Shanghai]', freq=None)

UTC DatetimeIndex:
DatetimeIndex(['2023-10-03 16:00:00+00:00', '2023-10-10 16:00:00+00:00',
               '2023-10-17 16:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq=None)

Original DatetimeIndex:
DatetimeIndex(['2023-10-04 00:00:00+08:00', '2023-10-11 00:00:00+08:00',
               '2023-10-18 00:00:00+08:00'],
              dtype='datetime64[ns, Asia/Shanghai]', freq=None)

In [45]:

# Create dates dataframe with frequency
data = pd.date_range('1/1/2011', periods = 10, freq ='H')

data

/tmp/ipykernel_666/1203082494.py:2: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  data = pd.date_range('1/1/2011', periods = 10, freq ='H')

DatetimeIndex(['2011-01-01 00:00:00', '2011-01-01 01:00:00',
               '2011-01-01 02:00:00', '2011-01-01 03:00:00',
               '2011-01-01 04:00:00', '2011-01-01 05:00:00',
               '2011-01-01 06:00:00', '2011-01-01 07:00:00',
               '2011-01-01 08:00:00', '2011-01-01 09:00:00'],
              dtype='datetime64[ns]', freq='h')

In [48]:
from datetime import datetime
data = pd.date_range('1/1/2011', periods=10, freq='h')
x = datetime.now()
print(x)
print(x.month, x.year)

2026-08-15 06:26:58.873398
8 2026

pandas.Series.dt.year returns the year of the date time.
pandas.Series.dt.month returns the month of the date time.
pandas.Series.dt.day returns the day of the date time.
pandas.Series.dt.hour returns the hour of the date time.
pandas.Series.dt.minute returns the minute of the date time.

In [49]:
#break data and time with data frame'
# Create date and time with dataframe
rng = pd.DataFrame()
rng['date'] = pd.date_range('1/1/2011', periods = 72, freq ='H')

# Print the dates in dd-mm-yy format
rng[:5]

# Create features for year, month, day, hour, and minute
rng['year'] = rng['date'].dt.year
rng['month'] = rng['date'].dt.month
rng['day'] = rng['date'].dt.day
rng['hour'] = rng['date'].dt.hour
rng['minute'] = rng['date'].dt.minute

# Print the dates divided into features
rng.head(3)

/tmp/ipykernel_666/650850971.py:4: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  rng['date'] = pd.date_range('1/1/2011', periods = 72, freq ='H')

                 date  year  month  day  hour  minute
0 2011-01-01 00:00:00  2011      1    1     0       0
1 2011-01-01 01:00:00  2011      1    1     1       0
2 2011-01-01 02:00:00  2011      1    1     2       0

In [53]:
#, use Timestamp.now() and then convert timestamp to datetime and directly access year, month or day.
# Input present datetime using Timestamp
pd.Timestamp.now()

Timestamp('2026-08-15 06:31:10.199026')

In [57]:
#Timestamp.timestamp in Pandas
import pandas as pd

# Create a Timestamp object
timestamp = pd.Timestamp("2022-10-12 12:30:45")

# Convert to Unix time
unix_time = timestamp.timestamp()

print("Unix Time:", unix_time)

Unix Time: 1665577845.0

In [58]:
#Creating timestamp objects with pandas
# Create the Timestamp object
ts = pd.Timestamp(year = 2026,  month = 11, day = 21,
                  hour = 10, second = 49, tz = 'US/Central')

# Print the Timestamp object
print(ts)
# return the number of seconds
ts.timestamp()

2026-11-21 10:00:49-06:00

1795276849.0

In [60]:
# Pandas Timestamp.now
#This function returns the current time in the local timezone
current_time = pd.Timestamp.now()

print("Current Timestamp:", current_time)

Current Timestamp: 2026-08-15 07:44:59.999972

In [62]:
#getting current time with timestamp objects in pandas
# Create the Timestamp object
ts = pd.Timestamp(year = 2026,  month = 8, day = 15,
           hour = 13, second = 49, tz = 'US/Central')
# Print the Timestamp object
print(ts)
# return the current time
ts.now()

2026-08-15 13:00:49-05:00

Timestamp('2026-08-15 07:46:46.432500')

In [63]:
#generating time stamps and creating time series
# Generate timestamps for the last 5 days
timestamps = pd.date_range(end=pd.Timestamp.now(), periods=5, freq="D")

# Create a DataFrame with timestamped data
data = {
    "timestamp": timestamps,
    "temperature": [21.2, 23.2, 27.2, 29.2, 31.2]
}
df = pd.DataFrame(data)

print(df)

                   timestamp  temperature
0 2026-08-11 07:47:27.244299         21.2
1 2026-08-12 07:47:27.244299         23.2
2 2026-08-13 07:47:27.244299         27.2
3 2026-08-14 07:47:27.244299         29.2
4 2026-08-15 07:47:27.244299         31.2

In [64]:
#Timestamp.isoformat
#function is used to convert the given Timestamp object into the ISO format.
# Create a Timestamp object in ISO format
time_stamp_obj = pd.Timestamp('2015-06-26 07:35:00', tz='Asia/Kolkata')

# Print the Timestamp object
print("Timestamp Object:", time_stamp_obj)

# Convert the Timestamp object to ISO format
iso_8601 = time_stamp_obj.isoformat()
print("ISO 8601 Format:", iso_8601)

Timestamp Object: 2015-06-26 07:35:00+05:30
ISO 8601 Format: 2015-06-26T07:35:00+05:30

In [66]:
# Timestamp.isoformat() function to convert the date in the given Timestamp object to ISO format.
# importing pandas as pd
# Create the Timestamp object
ts = pd.Timestamp(year = 2011,  month = 11, day = 21,
                  hour = 10, second = 49, tz = 'US/Central')

# Print the Timestamp object
print(ts)

2011-11-21 10:00:49-06:00

In [67]:
ts.isoformat()

'2011-11-21T10:00:49-06:00'

In [68]:
#Pandas Timestamp.date --> to return the date of the given Timestamp object as a datetime object.
# importing pandas as pd
# Create the Timestamp object
ts = pd.Timestamp(year = 2011,  month = 11, day = 21,
           hour = 10, second = 49, tz = 'US/Central')

# Print the Timestamp object
print(ts)

2011-11-21 10:00:49-06:00

In [69]:
ts.date()

datetime.date(2011, 11, 21)

In [ ]:
#Pandas Timestamp.replace
Syntax : Timestamp.replace()
Parameters :
year : int
month : int
day : int
hour : int
minute : int
second : int
microsecond : int
nanosecond : int
tzinfo : int
fold : int
Return : Timestamp with fields replaced

In [70]:
t = pd.Timestamp('2000-10-15 00:00:00')
t = t.replace(hour=13, minute=0, second=0)
print(t)

2000-10-15 13:00:00

In [71]:
#modifying year and month'
# Create a Timestamp object
timestamp = pd.Timestamp("2022-06-15 12:30:45")

# Replace the year
modified_timestamp = timestamp.replace(year=2023, month=10)

print("Org_Timestamp:", timestamp)
print("Mod_Timestamp:", modified_timestamp)

Org_Timestamp: 2022-06-15 12:30:45
Mod_Timestamp: 2023-10-15 12:30:45

In [73]:
# Timestamp.replace() function to replace the current year in the object
ts.replace(year = 2019)

Timestamp('2019-11-21 10:00:49-0600', tz='US/Central')

In [74]:
# Create the Timestamp object
ts = pd.Timestamp(year = 2009, month = 5, day = 31,
                  hour = 4, second = 49, tz = 'Europe/Berlin')

# Print the Timestamp object
print(ts)

2009-05-31 04:00:49+02:00

In [75]:
# replace year, month and hour value
ts.replace(year = 2019, month = 12, hour = 1)

Timestamp('2019-12-31 01:00:49+0100', tz='Europe/Berlin')

In [77]:
#.to_datetime() --> e. This function is essential for working with date and time data, especially when parsing strings or timestamps
d = ['2025-06-21', '2025-06-22']
res = pd.to_datetime(d)
print(res)

DatetimeIndex(['2025-06-21', '2025-06-22'], dtype='datetime64[ns]', freq=None)

arg

Input data to convert (e.g., scalar, list, Series, DataFrame).

errors

How to handle invalid parsing: 'raise' (default), 'coerce' (sets errors to NaT), 'ignore'.

format

Custom date format for parsing (e.g. "%d/%m/%Y")

dayfirst

If True, treats the first part of the date as the day (e.g., 31/12/2025).

yearfirst

If True, treats the first part as the year (e.g., 2025-12-31).

utc

If True, returns dates in UTC timezone.

unit

Specifies time unit if input is numeric ('s', 'ms', 'ns', etc.).

origin

Reference date for numeric timestamps ('unix' or a specific date like '1960-01-01').

cache

If True, enables caching to improve performance for repeated strings.

In [78]:
#.to_datetime() expects dates in ISO format (YYYY-MM-DD)
d = ['21/06/2025', '22/06/2025']
res = pd.to_datetime(d, format='%d/%m/%Y')
print(res)

DatetimeIndex(['2025-06-21', '2025-06-22'], dtype='datetime64[ns]', freq=None)

In [79]:
import pandas as pd
d = ['2025-06-21 12:00']
res = pd.to_datetime(d, utc=True)
print(res)

DatetimeIndex(['2025-06-21 12:00:00+00:00'], dtype='datetime64[ns, UTC]', freq=None)

Pandas.date_range() Syntax
Syntax: pandas.date_range(start=None, end=None, periods=None, freq=None, tz=None, normalize=False, name=None, closed=None, **kwargs)


Parameters:


start : Left bound for generating dates.


end : Right bound for generating dates.


periods : Number of periods to generate.


freq : Frequency strings can have multiples, e.g. ‘5H’. See here for a list of frequency aliases.


tz : Time zone name for returning localized DatetimeIndex. By default, the resulting DatetimeIndex is timezone-naive.


normalize : Normalize start/end dates to midnight before generating date range.


name : Name of the resulting DatetimeIndex.


closed : Make the interval closed with respect to the given frequency to the ‘left’, ‘right’, or both sides (None, the default).


Returns: DatetimeIndex

In [80]:
#Date_range() -->  It allows you to specify the starting date, ending date, frequency, and timezone for the generated dates, making it versatile for various time-based applications.

per1 = pd.date_range(start ='1-1-2018',
         end ='1-05-2018', freq ='5H')

for val in per1:
    print(val)

2018-01-01 00:00:00
2018-01-01 05:00:00
2018-01-01 10:00:00
2018-01-01 15:00:00
2018-01-01 20:00:00
2018-01-02 01:00:00
2018-01-02 06:00:00
2018-01-02 11:00:00
2018-01-02 16:00:00
2018-01-02 21:00:00
2018-01-03 02:00:00
2018-01-03 07:00:00
2018-01-03 12:00:00
2018-01-03 17:00:00
2018-01-03 22:00:00
2018-01-04 03:00:00
2018-01-04 08:00:00
2018-01-04 13:00:00
2018-01-04 18:00:00
2018-01-04 23:00:00

/tmp/ipykernel_666/147213635.py:3: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  per1 = pd.date_range(start ='1-1-2018',