<a href="https://colab.research.google.com/github/KBVYSHNAVI/Python/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([10,20,30,40,50,'abd'])
s

0     10
1     20
2     30
3     40
4     50
5    abd
dtype: object

In [ ]:
s.dtype

dtype('O')

In [ ]:
s.values

array([10, 20, 30, 40, 50, 'abd'], dtype=object)

In [ ]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
print(s.name)

None

In [ ]:
s.name = "calories"
s

0     10
1     20
2     30
3     40
4     50
5    abd
Name: calories, dtype: object

In [ ]:
#Indexing
s[0]

10

In [ ]:
s[0:2] #start(included):stop(excluded):step value(values to jump)

0    10
1    20
Name: numbers, dtype: object

In [ ]:
s[2:4]

2    30
3    40
Name: numbers, dtype: object

In [ ]:
#iloc =>location based indexes
s.iloc[3]

40

In [ ]:
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: numbers, dtype: object

In [ ]:
index = ["apple","banana","grapes","orange","strawberry"]

In [ ]:
s = pd.Series([10,20,30,40,50])
s.index = index
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
dtype: int64

In [ ]:
s.name = "calories"
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
Name: calories, dtype: int64

In [ ]:
s['grapes']

np.int64(30)

In [ ]:
#iloc can be used for int indexes
#loc=> label based indexing
#in label based indexing your start as well as stop value both are included in the output.

In [ ]:
s['banana':'orange']

banana    20
grapes    30
orange    40
Name: calories, dtype: int64

In [ ]:
#lets create a series using a dictionary
fruit_protein = {
    "Avacado": 2.0,
    "Guava" : 2.6,
    "Blackberries" : 2.0,
    "Orange" : 0.9,
    "Banana" : 1.1,
    "Apples" : 0.3,
    "Kiwi" : 1.1,
    "Promogranate" : 1.7,
    "Mango" : 0.8,
    "Cherrires" : 1.0
}

In [ ]:
s2 = pd.Series(fruit_protein)
s2

Avacado         2.0
Guava           2.6
Blackberries    2.0
Orange          0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Promogranate    1.7
Mango           0.8
Cherrires       1.0
dtype: float64

In [ ]:
s2 = pd.Series(fruit_protein,name = "Protein")
s2

Avacado         2.0
Guava           2.6
Blackberries    2.0
Orange          0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Promogranate    1.7
Mango           0.8
Cherrires       1.0
Name: Protein, dtype: float64

In [ ]:
#Conditional Selection
s2>1

Avacado          True
Guava            True
Blackberries     True
Orange          False
Banana           True
Apples          False
Kiwi             True
Promogranate     True
Mango           False
Cherrires       False
Name: Protein, dtype: bool

In [ ]:
s2[s2>1]

Avacado         2.0
Guava           2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Promogranate    1.7
Name: Protein, dtype: float64

In [ ]:
#logical Operators:and,or,not
#logical and :
      # True & True->True
      #True & False ->False
      #False & False -> False
#logical or:
      #True || True -> True
       #True || False ->True
       #False || False ->False

In [ ]:
s2[(s2>0.5)&(s2<2)]

Orange          0.9
Banana          1.1
Kiwi            1.1
Promogranate    1.7
Mango           0.8
Cherrires       1.0
Name: Protein, dtype: float64

In [ ]:
s2[(s2>0.5)|(s2<=2)]

Avacado         2.0
Guava           2.6
Blackberries    2.0
Orange          0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Promogranate    1.7
Mango           0.8
Cherrires       1.0
Name: Protein, dtype: float64

In [ ]:
#not operation
s2[~(s2>1)]

Orange       0.9
Apples       0.3
Mango        0.8
Cherrires    1.0
Name: Protein, dtype: float64

In [ ]:
#DataFrame
data = {
    "Name" :["yshu","harshitha","nithya","vasavi","joshna","hasini"],
    "Age" : [10,20,30,40,50,60],
    "Department" : ["HR","IT","Cloud Engineer","Devops Engineer","Finance","HR"],
    "Salary" : [250000,400000,260000,630000,58000,69000]
}

In [ ]:

data

{'Name': ['yshu', 'harshitha', 'nithya', 'vasavi', 'joshna', 'hasini'],
 'Age': [10, 20, 30, 40, 50, 60],
 'Department': ['HR',
  'IT',
  'Cloud Engineer',
  'Devops Engineer',
  'Finance',
  'HR'],
 'Salary': [250000, 400000, 260000, 630000, 58000, 69000]}

In [ ]:
import pandas as pd
df = pd.DataFrame(data)
df

        Name  Age       Department  Salary
0       yshu   10               HR  250000
1  harshitha   20               IT  400000
2     nithya   30   Cloud Engineer  260000
3     vasavi   40  Devops Engineer  630000
4     joshna   50          Finance   58000
5     hasini   60               HR   69000

In [ ]:
df.head(2) #for see top values

        Name  Age Department  Salary
0       yshu   10         HR  250000
1  harshitha   20         IT  400000

In [ ]:
df.tail(2) #for seeing last values

     Name  Age Department  Salary
4  joshna   50    Finance   58000
5  hasini   60         HR   69000

In [ ]:
#loc and iloc
df.iloc[1:3]

        Name  Age      Department  Salary
1  harshitha   20              IT  400000
2     nithya   30  Cloud Engineer  260000

In [ ]:
df.loc[1:3,["Age","Department"]]

   Age       Department
1   20               IT
2   30   Cloud Engineer
3   40  Devops Engineer

In [ ]:
#acceessing individual column
df[["Age","Name","Department"]]

   Age       Name       Department
0   10       yshu               HR
1   20  harshitha               IT
2   30     nithya   Cloud Engineer
3   40     vasavi  Devops Engineer
4   50     joshna          Finance
5   60     hasini               HR

In [ ]:
df.drop("Age",axis = 1) # axis value row = 0 column = 1

        Name       Department  Salary
0       yshu               HR  250000
1  harshitha               IT  400000
2     nithya   Cloud Engineer  260000
3     vasavi  Devops Engineer  630000
4     joshna          Finance   58000
5     hasini               HR   69000

In [ ]:
df.drop("Age",axis = 1,inplace = True)#inplace -> to perform the operation in the original data frame

In [ ]:
df

        Name       Department  Salary
0       yshu               HR  250000
1  harshitha               IT  400000
2     nithya   Cloud Engineer  260000
3     vasavi  Devops Engineer  630000
4     joshna          Finance   58000
5     hasini               HR   69000

In [ ]:
df.shape

(6, 3)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Department  6 non-null      object
 2   Salary      6 non-null      int64
dtypes: int64(1), object(2)
memory usage: 276.0+ bytes

In [ ]:
df.describe()#stastical operations

              Salary
count       6.000000
mean   277833.333333
std    215395.837162
min     58000.000000
25%    114250.000000
50%    255000.000000
75%    365000.000000
max    630000.000000

In [ ]:
#broadcasting
df["Salary"] = df["Salary"]+5000

In [ ]:
df

        Name       Department  Salary
0       yshu               HR  255000
1  harshitha               IT  405000
2     nithya   Cloud Engineer  265000
3     vasavi  Devops Engineer  635000
4     joshna          Finance   63000
5     hasini               HR   74000

In [ ]:
#renaming columns in data
df.rename(columns = {"Department" : "Dept"},inplace = True)

In [ ]:
df

        Name             Dept  Salary
0       yshu               HR  255000
1  harshitha               IT  405000
2     nithya   Cloud Engineer  265000
3     vasavi  Devops Engineer  635000
4     joshna          Finance   63000
5     hasini               HR   74000

In [ ]:
df["Dept"].unique()

array(['HR', 'IT', 'Cloud Engineer', 'Devops Engineer', 'Finance'],
      dtype=object)

In [ ]:
df["Dept"].value_counts()

Dept
HR                 2
IT                 1
Cloud Engineer     1
Devops Engineer    1
Finance            1
Name: count, dtype: int64

In [ ]:
#new column creation
df["Promoted Salary"] = df["Salary"]*10
df

        Name             Dept  Salary  Promoted Salary
0       yshu               HR  255000          2550000
1  harshitha               IT  405000          4050000
2     nithya   Cloud Engineer  265000          2650000
3     vasavi  Devops Engineer  635000          6350000
4     joshna          Finance   63000           630000
5     hasini               HR   74000           740000

In [ ]:
#data cleaning
df.isnull().sum()

Name               0
Dept               0
Salary             0
Promoted Salary    0
dtype: int64

In [ ]:
df.dropna(how = "any")#any  row that had any null value

        Name             Dept  Salary  Promoted Salary
0       yshu               HR  255000          2550000
1  harshitha               IT  405000          4050000
2     nithya   Cloud Engineer  265000          2650000
3     vasavi  Devops Engineer  635000          6350000
4     joshna          Finance   63000           630000
5     hasini               HR   74000           740000

In [ ]:
df.dropna(how = "all")#represents a particular row any row that had any null value was dropped
df

        Name             Dept  Salary  Promoted Salary
0       yshu               HR  255000          2550000
1  harshitha               IT  405000          4050000
2     nithya   Cloud Engineer  265000          2650000
3     vasavi  Devops Engineer  635000          6350000
4     joshna          Finance   63000           630000
5     hasini               HR   74000           740000

In [5]:
#filling those null values
import pandas as pd
data = {
    "Name" :["yshu","harshitha","nithya","vasavi","priya","hasini"],
    "Age" : [10,20,30,40,50,60],
    "Department" : ["HR","IT","Cloud Engineer","Devops Engineer","Finance","HR"],
    "Salary" : [250000,400000,260000,630000,58000,69000]
}
df = pd.DataFrame(data)
df.fillna(0)
print(df)

        Name  Age       Department  Salary
0       yshu   10               HR  250000
1  harshitha   20               IT  400000
2     nithya   30   Cloud Engineer  260000
3     vasavi   40  Devops Engineer  630000
4      priya   50          Finance   58000
5     hasini   60               HR   69000

In [6]:
df["Age"].fillna(df["Age"].mean())

0    10
1    20
2    30
3    40
4    50
5    60
Name: Age, dtype: int64

In [7]:
df["Salary"].fillna(df["Salary"].median)

0    250000
1    400000
2    260000
3    630000
4     58000
5     69000
Name: Salary, dtype: int64

In [8]:
df["Age"].fillna(method = "ffill")

/tmp/ipykernel_465/544980945.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method = "ffill")

0    10
1    20
2    30
3    40
4    50
5    60
Name: Age, dtype: int64

In [9]:
df

        Name  Age       Department  Salary
0       yshu   10               HR  250000
1  harshitha   20               IT  400000
2     nithya   30   Cloud Engineer  260000
3     vasavi   40  Devops Engineer  630000
4      priya   50          Finance   58000
5     hasini   60               HR   69000

In [10]:
df["Name"].replace("yshu","priya")

0        priya
1    harshitha
2       nithya
3       vasavi
4        priya
5       hasini
Name: Name, dtype: object

In [ ]:
#duplicates
df_dup = df[df.duplicated()]
df_dup

Empty DataFrame
Columns: [Name, Age, Department, Salary]
Index: []

In [ ]:
df

        Name  Age       Department  Salary
0       yshu   10               HR  250000
1  harshitha   20               IT  400000
2     nithya   30   Cloud Engineer  260000
3     vasavi   40  Devops Engineer  630000
4      priya   50          Finance   58000
5     hasini   60               HR   69000

In [11]:
df_dup = df[df.duplicated(keep = "first")]
df_dup

Empty DataFrame
Columns: [Name, Age, Department, Salary]
Index: []

In [ ]:
df_dup = df[df.duplicated(keep = "last")]
df_dup

Empty DataFrame
Columns: [Name, Age, Department, Salary]
Index: []

In [ ]:
df["Age"] = df["Age"].apply(lambda x: x *3 )

print(df)

        Name  Age       Department  Salary
0       yshu   60               HR  250000
1  harshitha  120               IT  400000
2     nithya  180   Cloud Engineer  260000
3     vasavi  240  Devops Engineer  630000
4      priya  300          Finance   58000
5     hasini  360               HR   69000

In [ ]:
df["Age"] = df["Age"].apply(lambda x: x /2 )

print(df)

In [13]:
df

        Name  Age       Department  Salary
0       yshu   10               HR  250000
1  harshitha   20               IT  400000
2     nithya   30   Cloud Engineer  260000
3     vasavi   40  Devops Engineer  630000
4      priya   50          Finance   58000
5     hasini   60               HR   69000

In [14]:
#joins and merges
import pandas as pd
department_info={
    "Dept" : ["HR","It","Finance"],
    "Location" : ["New York","Chicago","India"],
    "Manager" : ["Laura","Steve","Nina"]
}
df2 = pd.DataFrame(department_info)
df2

      Dept  Location Manager
0       HR  New York   Laura
1       It   Chicago   Steve
2  Finance     India    Nina

In [16]:
#concatenation
pd.concat([df,df2])

        Name   Age       Department    Salary     Dept  Location Manager
0       yshu  10.0               HR  250000.0      NaN       NaN     NaN
1  harshitha  20.0               IT  400000.0      NaN       NaN     NaN
2     nithya  30.0   Cloud Engineer  260000.0      NaN       NaN     NaN
3     vasavi  40.0  Devops Engineer  630000.0      NaN       NaN     NaN
4      priya  50.0          Finance   58000.0      NaN       NaN     NaN
5     hasini  60.0               HR   69000.0      NaN       NaN     NaN
0        NaN   NaN              NaN       NaN       HR  New York   Laura
1        NaN   NaN              NaN       NaN       It   Chicago   Steve
2        NaN   NaN              NaN       NaN  Finance     India    Nina

In [17]:
pd.concat([df,df2],axis=1)

        Name  Age       Department  Salary     Dept  Location Manager
0       yshu   10               HR  250000       HR  New York   Laura
1  harshitha   20               IT  400000       It   Chicago   Steve
2     nithya   30   Cloud Engineer  260000  Finance     India    Nina
3     vasavi   40  Devops Engineer  630000      NaN       NaN     NaN
4      priya   50          Finance   58000      NaN       NaN     NaN
5     hasini   60               HR   69000      NaN       NaN     NaN

In [21]:
pd.merge(df, df2, left_on="Department", right_on="Dept")

     Name  Age Department  Salary     Dept  Location Manager
0    yshu   10         HR  250000       HR  New York   Laura
1   priya   50    Finance   58000  Finance     India    Nina
2  hasini   60         HR   69000       HR  New York   Laura

Importing file

In [23]:
data = pd.read_csv("nba.csv")

In [25]:
data.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [26]:
data.shape

(458, 9)

In [31]:
data.iloc[100:105]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
100,Chris Paul,Los Angeles Clippers,3.0,PG,31.0,6-0,175.0,Wake Forest,21468695.0
101,Paul Pierce,Los Angeles Clippers,34.0,SF,38.0,6-7,235.0,Kansas,3376000.0
102,Pablo Prigioni,Los Angeles Clippers,9.0,PG,39.0,6-3,185.0,NaN,947726.0
103,JJ Redick,Los Angeles Clippers,4.0,SG,31.0,6-4,190.0,Duke,7085000.0
104,Austin Rivers,Los Angeles Clippers,25.0,PG,23.0,6-4,200.0,Duke,3110796.0

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [33]:
print(data.columns)

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')